config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'recipes#index'

  resources :ingredients

  resources :recipes do
    resources :ingredients
    resources :comments
  end

  resources :categories do
    resources :recipes
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  attr_accessor :quantity

  validates :title, :instructions, :description, presence: true
  has_attached_file :image, styles: { medium: "300x300>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :recipe_categories
  has_many :categories, through: :recipe_categories
  has_many :ingredients, through: :recipe_ingredients
  has_many :recipe_ingredients, dependent: :destroy
  has_many :comments
  belongs_to :user



  def self.recent
    order("recipes.updated_at DESC")
  end

  def comments_attributes=(comments_attributes)
    comments_attributes.values.each do |comment|
      if !(comments['content'] =="")
        self.comment << Comment.find_or_create_by(content: comment)
      end
    end
  end

  def ingredients_attributes=(ingredients_attributes)
    ingredients_attributes.each do |i, attribute|
      if (!(attribute.values.any? &:blank?))
        ingredient = Ingredient.find_or_create_by(name: attribute['name'])
        self.recipe_ingredients.build(ingredient_id: ingredient.id, quantity: attribute['quantity'])
      end
    end
  end

  def recipe_ingredients_attributes=(recipe_ingredients_attributes)
    recipe_ingredients_attributes.each do |i, attribute|
      if (!(attribute.values.any? &:blank?))
        self.recipe_ingredients.build(ingredient_id: attribute['id'].to_i, quantity: attribute['quantity'])
      else
        self.errors.add(:quantity, 'Oops, this can\'t be blank!')
      end
    end
  end

  def empty?
    attributes.values.compact.empty?
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!
  before_action :set_user, only:[:index, :show, :edit, :update]

  def index
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @recipes = @category.recipes
      @user_recipes = current_user.recipes
    else
      @recipe = Recipe.all
      @user_recipes = current_user.recipes
      @recipes = Recipe.recent.all
      respond_to do |format|
        format.html { render :index }
        format.json { render json: @recipe }
      end
    end
  end

  def new
    @recipe = current_user.recipes.build
    if params[:category_id]
      @category = Category.find(params[:category_id])
    end
    3.times do |i|
      @ingredient = @recipe.ingredients.build
    end
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @recipe.categories << @category
    end
    if @recipe.save
      redirect_to @recipe
    else
      3.times do |i|
        @ingredient = @recipe.ingredients.build
      end
      render 'new'
    end
  end

  def edit
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    if @recipe.persisted?
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def show
    @ingredients = @recipe.ingredients
    @comment = current_user.comments.build
    @comments = @recipe.comments
    @user = current_user
    @categories = @recipe.categories
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @recipe }
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: 'Deleted recipe successfully.'
  end

  private

	def set_recipe
		@recipe = Recipe.find(params[:id])
    @ingredient = @recipe.ingredients.build
    return @recipe, @ingredient
	end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :instructions, :image, category_ids: [], recipe_ingredients_attributes: [:id, :quantity, :_destroy], ingredients_attributes: [:id, :name, :quantity, :_destroy], comments_attributes: [:content])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_current_recipe_ingredients.html.erb
<div class='current-ingredients'>
  <% if !@recipe.id.nil? %>
    <% @recipe.recipe_ingredients.each do |current_ingredient| %>
      <li>
        <%= current_ingredient.ingredient.name %> <%= current_ingredient.quantity %>
        <%= link_to 'delete', recipe_ingredient_path(current_ingredient.recipe_id, current_ingredient.ingredient_id), :method => :delete, class: 'delete-ingredient' %>
      </li>
    <% end %>
  <% end %>
</div>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <% if @recipe.errors.any? %>
    <p>
      <%= @recipe.errors.count %> error(s) prevented your recipe from being saved.
    </p>
  <% end %>
  <br />
  <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>

  <br />

  <div class='form-new'>

      <%= f.text_field :title, placeholder: 'Title'%>

      <%= f.text_area :description, placeholder: 'Description'%>

      <%= f.file_field :image %>

      <%= f.text_area :instructions, placeholder: 'Instructions', rows: 8 %>  </div>

  <div class='categories'>
    <h3>Category:</h3>
    <p>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :title %>
    </p>
  </div>

  <div class="row">
    <div class='col-md-6'>
      <div class="ingredients-title">
        <h3>Ingredients:</h3>

        <%= render 'current_recipe_ingredients' %>

        <div id="ingredients">
          <%= f.fields_for :ingredients do |ff| %>

            <%= ff.label :name %>
            <%= ff.text_field :name %>

            <%= ff.label :quantity %>
            <%= ff.text_field :quantity %>


          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= f.button :submit, class: 'btn btn-primary form-submit' %>

<% end %>
</div>

app/views/recipes/edit.html.erb
<div class='main-content'>
  <h2>Edit Recipe</h2>
  <br />
  <br />
  <%= render 'form' %>
  <br />
  <%= link_to "back", root_path, class: "btn btn-default" %>
</div>

app/views/recipes/index.html.erb
<div class="index-main">
  <% if user_signed_in? %>
    <div class='your-recipes'>
        <h3>Your Recipes:</h3>
      <br />

      <% @user_recipes.each_slice(3) do |recipes| %>
        <div class="row">
          <% recipes.each do |recipe| %>
            <div class="col-md-4">
              <div class="recipe">
                <div class="image_wrapper">
                  <%= link_to recipe do %>
                    <%= image_tag recipe.image.url(:medium) %>
                    <div class='eyeicon'>

                    </div>
                  <% end %>
                </div>
                <h4>
                  <%= link_to recipe.title, recipe %>
                </h4>
                <button class="js-more" data-id="<%= recipe.id %>">Description</button>
                <div class="description-index recipeDescription_<%= recipe.id%>"></div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <br />
    <div class="all-recipes">
      <h3>All Recipes:</h3>

      <br />

      <% if current_user != @user %>
        <% @recipes.each_slice(3) do |all_recipes| %>
          <div class="row">
            <% all_recipes.each do |recipe| %>
              <div class="col-md-4">
                <div class="recipe">
                  <div class="image_wrapper">
                    <%= link_to recipe do %>
                      <%= image_tag recipe.image.url(:medium) %>
                    <% end %>
                  </div>
                  <h4>
                    <%= link_to recipe.title, recipe %>
                  </h4>
                  <button class="js-more" data-id="<%= recipe.id %>">Description</button>
                  <div class="no-show recipeDescription_<%= recipe.id%>"></div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h3>Oops, looks like you're not signed in...</h3>
    <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-default' %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default' %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class='main-content'>
  <h2>New Recipe</h2>
  <%= render 'form' %>
  <%= link_to "back", root_path, class: "btn btn-default back" %>
</div>

app/views/recipes/show.html.erb
<div class='main-content-show'>
  <div class='show-title-image'>
    <h2><%= @recipe.title%></h2>
    <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
  </div>

  <br />

  <div class='show-categories'>
   <h3>Categories:</h3><% @categories.each do |category| %>
     <%= link_to category.title, category_path(category) %>
   <% end %>
 </div>

  <div class='show-description'>
    <h3>Description:</h3>
    <p>
      <%= @recipe.description %>
    </p>
  </div>

  <div class='show-instructions'>
    <h3>Instructions:</h3>
    <p>
      <%= @recipe.instructions %>
    </p>
  </div>

  <div class='show-ingredients-directions'>

    <div class='show-ingredients'>
      <h3>Ingredients:</h3>
      <ul>
        <% @recipe.recipe_ingredients.each do |recipe_ingredient|%>
           <li><%= recipe_ingredient.quantity %> <%= recipe_ingredient.ingredient.name %></li>
         <%end%>
      </ul>
    </div>

    <br />

  </div>

  <div class='show-links'>
    <%= link_to "back", root_path, class: "btn btn-default" %>
    <% if current_user == @recipe.user %>
      <%= link_to "edit", edit_recipe_path(@recipe), class: "btn btn-default" %>
      <%= link_to "delete", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
    <% end %>
  </div>


  <div class='add-comment'>
    <h4>Comments: </h4>
    <%= form_for([@recipe, @comment]) do |f| %>
      <%= f.text_field :content, placeholder: 'Leave a comment...' %>
      <%= f.hidden_field :recipe_id, value: @recipe.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit 'add comment' %>
    <% end %>
  </div>


  <div id='comments'>
    <%= render 'comments/comments' %>
  </div>
</div>