config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'recipes#index'

  resources :ingredients

  resources :recipes do
    resources :ingredients
    resources :comments
  end

  resources :categories do
    resources :recipes
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes Share</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <nav class='navbar navbar-default'>
      <h1><%= link_to "Recipes Share", root_path %></h1>
      <div class='logo'>
      </div>
      <% if user_signed_in? %>
        <ul class='nav navbar-nav'>
            <li>
               <%= link_to "New Recipe", new_recipe_path %>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          </div>
        </ul>
        <% else %>
        <ul class ='nav navbar-nav'>
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        </ul>
        <% end %>
    </nav>
    <div class='dividingline'>

    </div>
    <div class='messages'>
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "alert" %>
        <% end %>
    </div>
    <%= yield %>
</body>
</html>